/**
 * API Fixtures for Playwright Tests
 *
 * These fixtures are generated by ink-api contract tests and pulled from S3.
 * They represent real API response structures and are used to mock API calls
 * in E2E tests, ensuring frontend expectations match actual backend responses.
 *
 * To update fixtures:
 *   1. Modify the API response in ink-api
 *   2. Update/add contract tests in ink-api/tests/Feature/Contracts/
 *   3. Push changes - fixtures auto-export to S3 when API files change
 *   4. Run `npm run pull:fixtures` to get latest fixtures
 *
 * See docs/api-fixtures.md for more details.
 */

// Artist fixtures
import artistDetail from './artist/detail.json';
import artistSearch from './artist/search.json';
import artistSettingsOwner from './artist/settings-owner.json';
import artistWorkingHours from './artist/working-hours.json';
import artistDashboardStats from './artist/dashboard-stats.json';

// Client dashboard fixtures
import clientDashboard from './client/dashboard.json';
import clientFavorites from './client/favorites.json';
import clientWishlist from './client/wishlist.json';
import clientSuggestedArtists from './client/suggested-artists.json';

// Tattoo fixtures
import tattooDetail from './tattoo/detail.json';
import tattooSearch from './tattoo/search.json';
import tattooCreateResponse from './tattoo/create-response.json';
import tattooUpdateResponse from './tattoo/update-response.json';

// User fixtures
import userProfile from './user/profile.json';
import userUpdateResponse from './user/update-response.json';

export const apiFixtures = {
  artist: {
    detail: artistDetail,
    search: artistSearch,
    settingsOwner: artistSettingsOwner,
    workingHours: artistWorkingHours,
    dashboardStats: artistDashboardStats,
  },
  client: {
    dashboard: clientDashboard,
    favorites: clientFavorites,
    wishlist: clientWishlist,
    suggestedArtists: clientSuggestedArtists,
  },
  tattoo: {
    detail: tattooDetail,
    search: tattooSearch,
    createResponse: tattooCreateResponse,
    updateResponse: tattooUpdateResponse,
  },
  user: {
    profile: userProfile,
    updateResponse: userUpdateResponse,
  },
};

// Type exports for TypeScript support
export type ArtistDetail = typeof artistDetail;
export type ArtistSearch = typeof artistSearch;
export type ClientDashboard = typeof clientDashboard;
export type TattooDetail = typeof tattooDetail;
export type UserProfile = typeof userProfile;
